version: '3.8'
services:
  order-service:
    build: ./order-service
    ports:
      - "8000:80"
    depends_on:
      - inventory-service
      - notification-service
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
  inventory-service:
    build: ./inventory-service
    ports:
      - "8001:80"
  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
